# Generated by Django 4.2.3 on 2024-05-17 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contactSpam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactDetails',
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileInfo',
        ),
    ]
